"""Add index column to Project model.

Revision ID: 09cc11e47b0b
Revises: 7b4c9e1b4c2c
Create Date: 2018-08-11 15:25:38.856364

"""
from alembic import op
from server import db
from server.models import Project


# revision identifiers, used by Alembic.
revision = '09cc11e47b0b'
down_revision = '7b4c9e1b4c2c'
branch_labels = None
depends_on = None


# pylint: disable=E1101
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', db.Column('index', db.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###
    index = 0
    projects = Project.query.all()
    for project in projects:
        index += 1
        project.index = index
    db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'index')
    # ### end Alembic commands ###
