"""empty message

Revision ID: 34bd80154607
Revises: 09cc11e47b0b
Create Date: 2018-08-18 03:51:53.324695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bd80154607'
down_revision = '09cc11e47b0b'
branch_labels = None
depends_on = None


# pylint: disable=E1101
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'blogpost',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=30), nullable=False),
        sa.Column('imgfile', sa.String(length=30), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('markdown', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogpost')
    # ### end Alembic commands ###
