"""empty message

Revision ID: 3d9039846508
Revises: 09cc11e47b0b
Create Date: 2018-08-17 18:44:06.571923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9039846508'
down_revision = '09cc11e47b0b'
branch_labels = None
depends_on = None


# pylint: disable=E1101
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'blogpost',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=30), nullable=False),
        sa.Column('imgfile', sa.String(length=30), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('markdown', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogpost')
    # ### end Alembic commands ###
